% DEFINE THE FAMILY OF CONTINUOUS, HOMOGENEOUS and ORDER-PRESERVING MAPS
A = [1,1;0,1];
B = [1,0;1,1];
b = 9/10;
F_1 = @(x) A*x;
F_2 = @(x) b*B*x;
F_family = {F_1,F_2};
F = @(x) F_1(F_2(x));

% THE SPECTRAL RADIUS IS COMPUTED USING polytopal_prenorm
% Compute spectral radius of F_1
[x,r]= pw_method(F,2,1000,1e-15);
% Proposed JSR
rho = r^(1/2);
% Run polytopal prenorm algorithm
[vertices,rho,info] = polytope_prenorm(F_family,x,rho,30);
%% DISPLAY THE EXTREMAL PRENORM and VERTICES THAT GENERATE IT (ORDERED AS THEY HAVE
%% BEEN GENERATED BY THE ALGORITHM
eps=1e-2; % displacement of text with respect to vertices
N_vertices=size(vertices,2);
[sortisci,Isort]=sort(vertices(1,:));
Y=vertices(:,Isort);
G=zeros(2,2*(N_vertices)+2);
G(:,2:2:2*(N_vertices))=Y(:,1:N_vertices);
G(2,1)=Y(2,1);
G(1,2*(N_vertices)+1)=Y(1,N_vertices);
for i=3:2:2*(N_vertices)-1
   G(:,i)=min(G(:,i-1),G(:,i+1));
end
pgon=polyshape(G(1,:),G(2,:));
f = figure('Color','w','Position',[100 100 800 700]);
ax = axes(f,'Position',[0.15 0.15 0.75 0.75]);
plot(ax, pgon)
hold(ax, 'on')
for i = 1:size(vertices,2)
    x = vertices(:,i);
    plot(ax, x(1), x(2), 'o', 'MarkerFaceColor','k',"MarkerSize", 12 , 'MarkerEdgeColor','k')
    text(ax, x(1)+eps, x(2)+eps, sprintf("x_{%d}",i), 'FontSize',18, 'Color','k', ...
         'HorizontalAlignment','left', 'VerticalAlignment','bottom')
end
title(ax, 'Extremal Prenorm', 'FontSize',18, 'Color','k')
axis(ax, [0 0.8 0 0.7])
drawnow
set(ax,'LooseInset',get(ax,'TightInset'))
drawnow
exportgraphics(f, fullfile("figures","extremal_prenorm.png"), 'Resolution', 300)


% COMPUTE EXTREMAL NORM
Nmax = 20;
[Y_hull, vertices,info] = polytope_norm(F_family,vertices(:,1),rho,Nmax);
% DISPLAY EXTREMAL NORM and VERTICES THAT GENERATE IT (ORDERED AS THEY HAVE
% BEEN GENERATED BY THE ALGORITHM
KH = convhull(Y_hull(1,:), Y_hull(2,:));
pgon=polyshape(Y_hull(1,:),Y_hull(2,:));
f = figure('Color','w','Position',[100 100 800 700]);
ax = axes(f,'Position',[0.15 0.15 0.75 0.75]);
plot(ax, pgon)
hold(ax, 'on')
for i = 4:size(vertices,2)
    x = vertices(:,i);
    plot(ax, x(1), x(2), 'o', 'MarkerFaceColor','k',"MarkerSize", 12 ,'MarkerEdgeColor','k')
    text(ax, x(1)+eps, x(2)+eps, sprintf("x_{%d}",i-3), 'FontSize',18, 'Color','k', ...
         'HorizontalAlignment','left', 'VerticalAlignment','bottom')
end
title(ax, 'Extremal Norm', 'FontSize',18, 'Color','k')
axis(ax, [0 0.8 0 0.7])
drawnow
set(ax,'LooseInset',get(ax,'TightInset'))
drawnow
exportgraphics(f, fullfile("figures","extremal_norm.png"), 'Resolution', 300)